### ISSUE TITLE
Styling changes to website

### ISSUE THREAD

**Issue by njmulsqb** [Tecvity/tecvity-nextjs#40]
As pointed out by @tayyubA there are certain changes in styling that can be made to the site
<img width="619" alt="image" src="https://github.com/user-attachments/assets/fb97c59e-144f-4bb6-86e4-5e7faac1994d">

@tayyubA assigning this to you for work on this, adjust as you see appropriate.

**Comment by tayyubA** [comment]
This issue will be resolved once the brand guidelines document of Tecvity is finalized, which is in progress but will take some.
ETA a month

**Comment by njmulsqb** [comment]
@tayyubA please create a corresponding task for it in Zoho projects if it doesnt already exists.

**Comment by tayyubA** [comment]
@njmulsqb noted
